pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'maven:3.6.0-jdk-8'
                    args '-v /root/.m2:/root/.m2'
                }
            }
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Security Scan') {
            agent {
                docker {
                    image 'trivy:latest'
                }
            }
            steps {
                sh 'trivy image $(docker build -q .)'
            }
        }
        stage('Dependency Check') {
            agent {
                docker {
                    image 'owasp/dependency-check:latest'
                }
            }
            steps {
                sh 'dependency-check --scan /app'
            }
        }
        stage('Sonar Analysis') {
            agent {
                docker {
                    image 'sonarqube:latest'
                }
            }
            steps {
                sh 'mvn sonar:sonar'
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'junit:latest'
                }
            }
            steps {
                sh 'mvn test'
            }
        }
    }
}